stages:
  - build
  - push-image

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA


build-admin-api:
  stage: build
  image: eclipse-temurin:21-alpine
  script:
    - cd admin-api
    - ./gradlew build
  artifacts:
    paths:
      - admin-api/build/libs/
    expire_in: 30 min

push-admin-api:
  stage: push-image
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      variables:
        HEALTHCHECK_TCP_PORT: "2375"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker buildx create --use || echo "buildx already exists"
  script:
    - cd admin-api
    - ls -l build/libs
    - |
      docker buildx build --platform linux/arm64 \
      -t $CI_REGISTRY_IMAGE/admin-api:$CI_COMMIT_SHORT_SHA \
      -t $CI_REGISTRY_IMAGE/admin-api:latest \
      --push .

build-admin:
  stage: push-image
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      variables:
        HEALTHCHECK_TCP_PORT: "2375"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker buildx create --use || echo "buildx already exists"
  script:
    - cd admin
    - |
      docker buildx build --platform linux/arm64 \
      -t $CI_REGISTRY_IMAGE/admin:$CI_COMMIT_SHORT_SHA \
      -t $CI_REGISTRY_IMAGE/admin:latest \
      --push .
