services:
  dev-container:
    image: "mcr.microsoft.com/devcontainers/java:1-21-bullseye"
    networks:
      - redis-net

  db:
    image: postgres:latest
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dornol_ticket
    ports:
      - "5432:5432"
    networks:
      - redis-net

  redis-master:
    image: redis:7.4
    container_name: redis-master
    command: [ "redis-server", "--appendonly", "yes", "--protected-mode", "no" ]
    networks:
      redis-net:
        ipv4_address: ${REDIS_MASTER_IP}

  redis-replica-1:
    image: redis:7.4
    container_name: redis-replica-1
    depends_on:
      - redis-master
    command: [ "redis-server", "--replicaof", "${REDIS_MASTER_IP}", "6379", "--protected-mode", "no" ]
    networks:
      redis-net:
        ipv4_address: ${REDIS_REPLICA_1_IP}

  redis-replica-2:
    image: redis:7.4
    container_name: redis-replica-2
    depends_on:
      - redis-master
    command: [ "redis-server", "--replicaof", "${REDIS_MASTER_IP}", "6379", "--protected-mode", "no" ]
    networks:
      redis-net:
        ipv4_address: ${REDIS_REPLICA_2_IP}

  sentinel-1:
    image: redis:7.4
    container_name: redis-sentinel-1
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    command: >
      sh -c 'echo "sentinel resolve-hostnames no" > /etc/sentinel.conf &&
            echo "sentinel monitor mymaster ${REDIS_MASTER_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds mymaster 1000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout mymaster 5000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
            redis-server /etc/sentinel.conf --sentinel'
    networks:
      redis-net:
        ipv4_address: ${REDIS_SENTINEL_1_IP}

  sentinel-2:
    image: redis:7.4
    container_name: redis-sentinel-2
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    command: >
      sh -c 'echo "sentinel resolve-hostnames no" > /etc/sentinel.conf &&
            echo "sentinel monitor mymaster ${REDIS_MASTER_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds mymaster 1000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout mymaster 5000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
            redis-server /etc/sentinel.conf --sentinel'
    networks:
      redis-net:
        ipv4_address: ${REDIS_SENTINEL_2_IP}

  sentinel-3:
    image: redis:7.4
    container_name: redis-sentinel-3
    depends_on:
      - redis-master
      - redis-replica-1
      - redis-replica-2
    command: >
      sh -c 'echo "sentinel resolve-hostnames no" > /etc/sentinel.conf &&
            echo "sentinel monitor mymaster ${REDIS_MASTER_IP} 6379 2" >> /etc/sentinel.conf &&
            echo "sentinel down-after-milliseconds mymaster 1000" >> /etc/sentinel.conf &&
            echo "sentinel failover-timeout mymaster 5000" >> /etc/sentinel.conf &&
            echo "sentinel parallel-syncs mymaster 1" >> /etc/sentinel.conf &&
            redis-server /etc/sentinel.conf --sentinel'
    networks:
      redis-net:
        ipv4_address: ${REDIS_SENTINEL_3_IP}

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${REDIS_NET_SUBNET}
          gateway: ${REDIS_NET_GATEWAY}