services:
  db:
    image: postgres:latest
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dornol_ticket
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"