spring:
  application:
    name: admin-api


  data:
    redis:
      cluster:
        max-redirects: 3
        nodes:
          - redis-node-0:6379
          - redis-node-1:6379
          - redis-node-2:6379
          - redis-node-3:6379
          - redis-node-4:6379
          - redis-node-5:6379

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: "****"
    username: "****"
    password: "****"
    hikari:
      data-source-properties:
        ApplicationName: AdminApi${NODE-ID}
      keepalive-time: 600000

dornol:
  properties:
    cloud:
      s3:
        endpoint: http://minio:9000
  security:
    cors:
      allowed-origins: https://admin.ticket.dornol.dev
    jwt:
      rsa:
        public-key: "classpath:certs/public.pem"
        private-key: "classpath:certs/private.pem"
      access-token:
        expiry-seconds: 900
      refresh-token:
        expiry-seconds: 1209600

logging:
  config: classpath:logback-json-config.xml