spring:
  application:
    name: admin-api

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: "****"
    username: "****"
    password: "****"

dornol:
  security:
    cors:
      allowed-origins: https://admin.ticket.dornol.dev
    jwt:
      rsa:
        public-key: "classpath:certs/public.pem"
        private-key: "classpath:certs/private.pem"
      access-token:
        expiry-seconds: 900
      refresh-token:
        expiry-seconds: 1209600