spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dornol_ticket
    username: postgres
    password: postgres

  flyway:
    enabled: true

  jpa:
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379


server:
  servlet:
    context-path: /api/v1
logging:
  level:
    dev.dornol: debug


dornol:
  security:
    jwt:
      access-token:
        expiry-seconds: 10
      refresh-token:
        expiry-seconds: 120


node-id: 0