spring:
  datasource:
    url: jdbc:postgresql://db:5432/dornol_ticket
    username: postgres
    password: postgres

  flyway:
    enabled: true

  jpa:
    show-sql: true

  data:
    redis:
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 30s
            dynamic-refresh-sources: true
      sentinel:
        master: mymaster
        nodes:
          - redis-sentinel-1:26379
          - redis-sentinel-2:26379
          - redis-sentinel-3:26379

server:
  servlet:
    context-path: /api/v1
logging:
  level:
    dev.dornol: debug
    io.lettuce.core: DEBUG
    org.springframework.data.redis.connection.lettuce: DEBUG

dornol:
  security:
    jwt:
      access-token:
        expiry-seconds: 10
      refresh-token:
        expiry-seconds: 3600


node-id: 0