spring:
  application:
    name: admin-api

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5432/dornol_ticket
    username: postgres
    password: postgres

  jpa:
    open-in-view: false

dornol:
  security:
    cors:
      allowed-origins: http://localhost:8080
    jwt:
      rsa:
        public-key: "classpath:certs/public.pem"
        private-key: "classpath:certs/private.pem"
      access-token:
        expiry-seconds: 1800
      refresh-token:
        expiry-seconds: 1209600

