spring:
  application:
    name: admin-api

  data:
    redis:
      host: dornol_ticket_redis
      port: 6379

  datasource:
    url: jdbc:postgresql://dornol_ticket_db/dornol_ticket
    username: postgres
    password: postgres