spring:
  application:
    name: admin-api

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: "****"
    username: "****"
    password: "****"