spring:
  application:
    name: admin-api

  data:
    redis:
      host: localhost
      port: 6379
    web:
      pageable:
        size-parameter: pageSize
        page-parameter: pageIndex
        serialization-mode: via_dto

  datasource:
    url: jdbc:postgresql://localhost:5432/dornol_ticket
    username: postgres
    password: postgres

  jpa:
    open-in-view: false

  messages:
    basename: messages, errors
    use-code-as-default-message: true
    encoding: UTF-8



server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

dornol:
  security:
    cors:
      allowed-origins: http://localhost:8080,http://localhost:3000
    jwt:
      rsa:
        public-key: "classpath:certs/public.pem"
        private-key: "classpath:certs/private.pem"
      access-token:
        expiry-seconds: 3600
      refresh-token:
        expiry-seconds: 1209600