spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dornol_ticket
    username: postgres
    password: postgres

  flyway:
    enabled: true

  jpa:
    show-sql: true

  data:
    redis:
      sentinel:
        master: mymaster
        nodes:
          - 127.0.0.1:33310
          - 127.0.0.1:33311
          - 127.0.0.1:33312


server:
  servlet:
    context-path: /api/v1
logging:
  level:
    dev.dornol: debug


dornol:
  security:
    jwt:
      access-token:
        expiry-seconds: 10
      refresh-token:
        expiry-seconds: 3600


node-id: 0