spring:
  application:
    name: admin-api

  data:
    web:
      pageable:
        size-parameter: pageSize
        page-parameter: pageIndex
        serialization-mode: via_dto

  datasource:
    url: jdbc:h2:mem:dornol_ticket

  jpa:
    open-in-view: false

  messages:
    basename: messages, errors
    encoding: UTF-8



server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

dornol:
  properties:
    cloud:
      s3:
        base-url: https://s3.dornol.dev
        endpoint: https://s3.dornol.dev
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
  security:
    cors:
      allowed-origins: http://localhost:8080,http://localhost:3000
    jwt:
      rsa:
        public-key: "classpath:certs/public.pem"
        private-key: "classpath:certs/private.pem"
      access-token:
        expiry-seconds: 3600
      refresh-token:
        expiry-seconds: 1209600

node-id: 0