spring:
  flyway:
    enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

  data:
    redis:
      host: localhost
      port: 6379


server:
  servlet:
    context-path: /api/v1
logging:
  level:
    dev.dornol: debug

node-id: 0