name: Module Versioning

on:
  push:
    branches:
      - main

jobs:
  check-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 태그 정보를 가져오기 위해 전체 히스토리 필요

      - name: Check changed modules
        id: changed_modules
        run: |
          MODULES=("modules/admin-api" "modules/api" "modules/domain" "modules/core")
          CHANGED_MODULES=()

          for MODULE in "${MODULES[@]}"; do
            if git diff --name-only HEAD~1 | grep -q "^$MODULE/"; then
              CHANGED_MODULES+=("$MODULE")
            fi
          done

          echo "Changed modules: ${CHANGED_MODULES[@]}"
          echo "changed_modules=${CHANGED_MODULES[*]}" >> $GITHUB_ENV

      - name: Get latest tag and create new tag for changed modules
        if: env.changed_modules != ''
        run: |
          for MODULE in ${{ env.changed_modules }}; do
            MODULE_NAME=$(basename $MODULE)
            latest_tag=$(git tag -l "${MODULE_NAME}-v*" | sort -V | tail -n 1)

            if [ -z "$latest_tag" ]; then
              new_tag="${MODULE_NAME}-v1.0.0"
            else
              version=$(echo $latest_tag | sed 's/.*-v//')
              major=$(echo $version | cut -d. -f1)
              minor=$(echo $version | cut -d. -f2)
              patch=$(echo $version | cut -d. -f3)
              new_patch=$((patch + 1))
              new_tag="${MODULE_NAME}-v$major.$minor.$new_patch"
            fi

            echo "New tag for $MODULE_NAME: $new_tag"
            git tag "$new_tag"
            git push origin "$new_tag"
          done